config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: :commentable, defaults: { commentable: 'question' } do
    resources :answers, concerns: :commentable, defaults: { commentable: 'answer' }, shallow: true do
      post 'best', on: :member
    end
  end

  resources :votes do
    post 'like', on: :collection
    post 'dislike', on: :collection
  end

  resources :attachments, only: :destroy

  root to: "questions#index" 

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, :body, :user_id, presence: true
  validates :title, length: 5..140
  validates :body, length: 15..1050

  accepts_nested_attributes_for :attachments, reject_if: proc { |attrib| attrib['file'].nil? }

  def answer_best
    @ex_best = answers.where(best: true).first
  end

end    

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!, except: [:show, :index]
	before_action :load_question, only: [:show, :update, :destroy]
	before_action :save_current_user, only: [:show, :index]

	def index
		@questions = Question.all
	end

	def show
		@answers = @question.answers
	end

	def new
		@question = Question.new
	end

	def update
		flash[:notice] = "Question successfully updated!" if @question.user_id == current_user.id && @question.update(question_params)
	end

	def create
		@question = Question.create(question_params)
		@question.user = current_user
		  if @question.save
		  	PrivatePub.publish_to '/questions/index', question: @question.to_json
	        redirect_to question_path(@question), flash: { notice: "Question successfully created!"}
	      else
		    render :new
	      end
	end

	def destroy
		@question.destroy if @question.user_id == current_user.id
		redirect_to questions_path
	end

	private

	def load_question
		@question = Question.find(params[:id])
	end

	def question_params
		params.require(:question).permit(:title, :body, attachments_attributes:[:file])
	end

    def save_current_user
	    if user_signed_in?
	      gon.current_user = current_user.id if user_signed_in?
	      gon.question_author = @question.user_id if @question
	    end
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .file
    = f.label :file
    = f.file_field :file
  = link_to_remove_association "Remove file", f

app/views/questions/_question.html.slim
.question id = "question-#{@question.id}" data = { question_id: "#{@question.id}" }
  h1= @question.title
  h2= @question.body
  .question-vote id = "question-#{@question.id}-vote"
    p= "Votes:#{@question.rate}"
    - if user_signed_in? && @question.user_id != current_user.id
      - if @question.votes.find_by(user: current_user)
        = link_to 'Cancel vote', vote_path(@question.votes.find_by(user: current_user)), method: :delete, remote: true, data: { type: :json }, class: 'vote-cancel'
      - else
        = link_to 'Like', like_votes_path(votable: @question.id, votable_type: @question.model_name), method: :post, remote: true, data: { type: :json }, class: 'vote-set'
        br
        = link_to 'Dislike', dislike_votes_path(votable: @question.id, votable_type: @question.model_name), method: :post, remote: true, data: { type: :json }, class: 'vote-set'
  p= 'Attachments:'
  ul
    - @question.attachments.find_each do |a|
      .attachment id = "attachment-#{a.id}"
        li= link_to a.file.identifier, a.file.url
        = link_to 'Remove file', attachment_path(a), method: :delete, remote: true if user_signed_in? && current_user.id == @question.user_id
  - if user_signed_in? && current_user.id == @question.user_id
    p= link_to 'Edit', '', class: 'edit-question-link', data: { question_id: @question.id }
    = form_for @question, html: { id: "edit-question-#{@question.id}"}, remote: true do |f_q|
      = f_q.label :body
      .question_errors
      = f_q.text_area :body
      = f_q.submit 'Save'
 
  = render 'comments/comments', commentable: @question

  = subscribe_to "/question/#{@question.id}/comments" 

app/views/questions/index.html.slim
= link_to 'Ask a question', new_question_path
.questions
  -@questions.find_each do |q|
    = link_to q.title, question_path(q)
    br
    = link_to 'Delete', question_path(q), method: :delete if user_signed_in? && q.user_id == current_user.id
    p

= subscribe_to "/questions/index" 

app/views/questions/new.html.slim
= form_for @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body, 'Text'
  = f.text_area :body
  = f.fields_for :attachments do |attachment|
  .links
    = link_to_add_association 'Add file', f, :attachments
  = f.submit 'Save a question'

app/views/questions/show.html.slim
= render @question

h3= 'Answers:'

.answers 
  = render @answers
      
- if user_signed_in?
    br
    .new_answer_errors
      br
    = form_for [@question, Answer.new], remote: true do |f|
      = f.label :body, 'Text'
      p= f.text_area :body
      = f.fields_for :attachments do |attachment|
      .links
        = link_to_add_association 'Add file', f, :attachments
      = f.submit 'Give an answer'

= subscribe_to "/questions/#{@question.id}/answers"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
    <%@question.errors.full_messages.each do |message|%>
        $('.question_errors').append('<p> <%= j message %></p>')
    <% end %>
<% else %>
    $('.question').html('<%= j render @question %>')
    $('.notice').html('<%= j flash[:notice]%>')
    $('.edit-question-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        question_id = $(this).data('questionId');
        $('form#edit-question-' + question_id).show();
    })
<% end %>