config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: :commentable, defaults: { commentable: 'question' } do
    resources :answers, concerns: :commentable, defaults: { commentable: 'answer' }, shallow: true do
      post 'best', on: :member
    end
  end

  resources :votes do
    post 'like', on: :collection
    post 'dislike', on: :collection
  end

  resources :attachments, only: :destroy

  root to: "questions#index" 

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  default_scope { order('best DESC') }

  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, :question_id, :user_id, presence: true
  validates :body, length: 5..1500

  accepts_nested_attributes_for :attachments, reject_if: proc { |attrib| attrib['file'].nil? }

  def mark_as_best
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:best, :update, :destroy]
  respond_to :json, :js

  def best
    @question = Question.where(params[:question_id]).first
    @ex_best = @question.answer_best
    @answer.mark_as_best if @answer.user_id == current_user.id
    @ex_best.reload if @ex_best
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user

    if @answer.save
      flash[:notice] = "Answer successfully added!"
      PrivatePub.publish_to "/questions/#{@answer.question_id}/answers", answer: @answer.to_json, attachments: @answer.attachments
      respond_with(@answer.to_json, location: question_path(@question) )
    else
      respond_with(@answer, status: :unprocessable_entity)
    end
  end

  def update
    flash[:notice] = "Answer successfully updated!" if @answer.user_id == current_user.id && @answer.update(answer_params)  
  end

  def destroy
    flash[:notice] = "Answer successfully destroyed!" if @answer.user_id == current_user.id && @answer.destroy
  end

  private

  def load_question
     @question = Question.find(params[:question_id])
   end
 
   def load_answer
     @answer = Answer.find(params[:id])
   end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes:[:file])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer id = "answer-#{answer.id}"
  .answer_errors
  h4= answer.body
  .answer-vote id = "answer-#{answer.id}-vote"
    p= "Votes:#{answer.rate}"
    - if user_signed_in? && answer.user_id != current_user.id
      - if answer.votes.find_by(user: current_user)
        = link_to 'Cancel vote', vote_path(answer.votes.find_by(user: current_user)), method: :delete, remote: true, data: {type: :json}, class: 'vote-cancel'
      - else
        = link_to 'Like', like_votes_path(votable: answer.id, votable_type: answer.model_name), method: :post, remote: true, data: {type: :json}, class: 'vote-set'
        br
        = link_to 'Dislike', dislike_votes_path(votable: answer.id, votable_type: answer.model_name), method: :post, remote: true, data: {type: :json}, class: 'vote-set'
  p= 'Attachments:'
  ul
    - answer.attachments.find_each do |a|
      .attachment id = "attachment-#{a.id}"
        li= link_to a.file.file.identifier, a.file.url
        = link_to 'Remove file', attachment_path(a), method: :delete, remote: true  if user_signed_in? && current_user.id == answer.user_id
  - if user_signed_in? 
      - if answer.question.user_id == current_user.id
        = answer.best ?  'Best' : link_to("Mark as best", best_answer_path(answer), method: :post, remote: true)
        br
      - if answer.user_id == current_user.id
        = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        br
        = form_for answer, html: { id: "edit-answer-#{answer.id}" }, remote: true do |f|
          = f.label :body
          = f.text_area :body
          = f.submit 'Save'
        = link_to 'Delete', answer_path(answer), method: :delete, remote: true if user_signed_in? && answer.user_id == current_user.id 

  = render 'comments/comments', commentable: answer
  = subscribe_to "/question/#{answer.question_id}/comments"

app/views/answers/best.js.erb
$("#answer-<%= @answer.id %>").remove();
$('<%= j render @answer %>').prependTo( $('.answers'));
<% if @ex_best %>
    $("#answer-<%= @ex_best.id %>").replaceWith('<%= j render @ex_best%>')
<% end %> 

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
    $('.new_answer_errors').html('');
    <%@answer.errors.full_messages.each do |message|%>
        $('.new_answer_errors').append('<p> <%= j message %></p>');
    <% end %>
<% end %>

$('textarea#answer_body').val('');

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
    <%@answer.errors.full_messages.each do |message|%>
        $("#answer-<%= @answer.id %> .answer_errors").append('<p> <%= j message %></p>')
    <% end %>
<% else %>
    $("#answer-<%= @answer.id %>").remove()
    $('.notice').html('<%= j flash[:notice]%>')
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <%@answer.errors.full_messages.each do |message|%>
        $("#answer-<%= @answer.id %> .answer_errors").append('<p> <%= j message %></p>')
    <% end %>
<% else %>
    $("#answer-<%= @answer.id %>").replaceWith('<%= j render @answer %>')
    $('.notice').html('<%= j flash[:notice]%>')
    $('.edit-answer-link').click(function (e) {
        e.preventDefault();
        $(this).hide();
        answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
    })
<% end %>